version: "3.7"
services:
  database_ignite:
    image: postgres
    container_name: "database_rentx"
    restart: always
    network_mode: "host"
    # ports:
    #   - 2000:2000
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD= 123456
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    network_mode: "host"
    # ports:
    #   - 3333:3333
    volumes:
      - .:/usr/app
    

volumes:
  pgdata:
    driver: local